### ISSUE TITLE
Could not create path: 'Documents/Data/02_reference_alignment

### ISSUE THREAD

**Issue by alexa488** [barricklab/barricklab#1]
Hi, I've been trying to use breseq but keep getting this message "Could not create path: 'Documents/Data/02_reference_alignment'.  How should I go about it? The full version is given below:

breseq -r Documents/Data/Newman.fasta Documents/Data/NMtagO_1_1_trimmed.fastq.gz Documents/Data/NMtagO_1_2_trimmed.fastq.gz -o Documents/Data
================================================================================
breseq 0.31.0  revision 69e7c3c0fa11   http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2017 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G.
  (2014) Identifying structural variation in haploid microbial genomes
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.2.6 [/usr/bin/bowtie2]
---> R        :: version 3.4.1 [/usr/bin/R]
+++   NOW PROCESSING Read and reference sequence file input
----------------------------------> WARNING <-----------------------------------
Reference seq id converted from 'gi|150373012|dbj|AP009351.1|' to 'gi_150373012_dbj_AP009351.1'.
Only alphanumeric characters, periods, dashes, and single underscores '_' are allowed in seq ids.
--------------------------------------------------------------------------------
  READ FILE::NMtagO_1_1_trimmed
    Converting/filtering FASTQ file...
    Original base quality format: SANGER New format: SANGER
    Original reads: 2555738 bases: 613772470
    Filtered reads: none
    Analyzed reads: 2555738 bases: 613772470
  READ FILE::NMtagO_1_2_trimmed
    Converting/filtering FASTQ file...
    Original base quality format: SANGER New format: SANGER
    Original reads: 2555738 bases: 579416927
    Filtered reads:       3 bases:       540 (≥90.0% same base)
    Analyzed reads: 2555735 bases: 579416387
  ::TOTAL::
    Original reads: 5111476 bases: 1193189397
    Analyzed reads: 5111473 bases: 1193188857
[samtools] faidx Documents/Data/data/reference.fasta
+++   NOW PROCESSING Read alignment to reference genome
Could not create path: 'Documents/Data/02_reference_alignment'

**Comment by jeffreybarrick** [comment]
It's odd that it would complete the first step and only then this would appear. An error like this usually indicates a permissions error. What are the results of `ls -l` on `Documents/Data`?

**Comment by alexa488** [comment]
ls -l Documents/Data
total 1487236
drwxrwxr-x 2 aleksandra aleksandra      4096 Oct  8 19:24 01_sequence_conversion
drwxrwxr-x 2 aleksandra aleksandra      4096 Oct  8 19:24 data
-rw-rw-r-- 1 aleksandra aleksandra   2920125 Oct  5 15:27 Newman.fasta
-rw-rw-r-- 1 aleksandra aleksandra  78981875 May  3 07:40 NewmanTCD_1_trimmed.fastq.gz
-rw-rw-r-- 1 aleksandra aleksandra  91945588 May  3 07:40 NewmanTCD_2_trimmed.fastq.gz
-rw-rw-r-- 1 aleksandra aleksandra 481826660 May  3 07:40 NMtagO_1_1_trimmed.fastq.gz
-rw-rw-r-- 1 aleksandra aleksandra 487869640 May  3 07:40 NMtagO_1_2_trimmed.fastq.gz
-rw-rw-r-- 1 aleksandra aleksandra 175681840 May  3 07:40 NMtagO_2_1_trimmed.fastq.gz
-rw-rw-r-- 1 aleksandra aleksandra 203672952 May  3 07:40 NMtagO_2_2_trimmed.fastq.gz
drwxrwxr-x 2 aleksandra aleksandra      4096 Oct  8 19:21 output

**Comment by jeffreybarrick** [comment]
My only other guess is that your hard drive is full. Are you able to `mkdir Documents/Data/02_reference_alignment`. That's essentially what _breseq_ is attempting to do. Maybe try running this again with a different -o output path?

**Comment by alexa488** [comment]
I've cleaned up the hard drive and run it again with a different output path as suggested. The same error came up.
I got back to  "mkdir Documents/Data/02_reference_alignment", but it's still not running as it should. It seems there is a problem with the bowtie2. The results are below:

aleksandra@aleksandra-VirtualBox:~$ mkdir Documents/Data/02_reference_alignment
aleksandra@aleksandra-VirtualBox:~$ breseq -r Documents/Data/Newman.fasta Documents/Data/NMtagO_1_1_trimmed.fastq.gz Documents/Data/NMtagO_1_2_trimmed.fastq.gz -o Documents/Data
================================================================================
breseq 0.31.0  revision 69e7c3c0fa11   http://barricklab.org/breseq

Active Developers: Barrick JE, Deatherage DE
Contact:           <jeffrey.e.barrick@gmail.com>

breseq is free software; you can redistribute it and/or modify it under the
terms the GNU General Public License as published by the Free Software 
Foundation; either version 2, or (at your option) any later version.

Copyright (c) 2008-2010 Michigan State University
Copyright (c) 2011-2017 The University of Texas at Austin

If you use breseq in your research, please cite:

  Deatherage, D.E., Barrick, J.E. (2014) Identification of mutations
  in laboratory-evolved microbes from next-generation sequencing
  data using breseq. Methods Mol. Biol. 1151: 165–188.

If you use structural variation (junction) predictions, please cite:

  Barrick, J.E., Colburn, G., Deatherage D.E., Traverse, C.C.,
  Strand, M.D., Borges, J.J., Knoester, D.B., Reba, A., Meyer, A.G. 
  (2014) Identifying structural variation in haploid microbial genomes 
  from short-read resequencing data using breseq. BMC Genomics 15:1039.
================================================================================
---> bowtie2  :: version 2.2.6 [/usr/bin/bowtie2]
---> R        :: version 3.4.1 [/usr/bin/R]
--- ALREADY COMPLETE Read and reference sequence file input
+++   NOW PROCESSING Read alignment to reference genome
[system] bowtie2-build -q Documents/Data/data/reference.fasta Documents/Data/02_reference_alignment/reference
Building a SMALL index
Error writing to the reference index file (.4.ebwt)
Error: Encountered internal Bowtie 2 exception (#1)
Command: bowtie2-build --wrapper basic-0 -q Documents/Data/data/reference.fasta Documents/Data/02_reference_alignment/reference 
Deleting "Documents/Data/02_reference_alignment/reference.3.bt2" file written during aborted indexing attempt.
Deleting "Documents/Data/02_reference_alignment/reference.4.bt2" file written during aborted indexing attempt.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> FATAL ERROR <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Error running command:
[system] bowtie2-build -q Documents/Data/data/reference.fasta Documents/Data/02_reference_alignment/reference
Result code: 256
FILE: libbreseq/common.h   LINE: 1477
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!> STACK TRACE <!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
0x00000000004291f7 _ZN6breseq6SYSTEMESsbbb
0x000000000041eeb8 _Z21breseq_default_actioniPPc
0x0000000000427155 main
0x00007f3ecb6a6830 __libc_start_main
0x0000000000409eed _start
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by jeffreybarrick** [comment]
Your hard drive is running out of space or your account's allocated disk space is exhausted during the _breseq_ run. This is why different steps fail when they try to create a file or folder. Make sure you have >10x the size of the input FASTQ files in free space before starting the _breseq_ run.

**Comment by alexa488** [comment]
Thanks a million for all your help!
